/* Generates src/data/index.generated.ts: light records for the journey page so long-form story text stays in lazy chunks. */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { arcs } from '../src/data/arcs';
import { locations } from '../src/data/locations';

const arcSummaries = arcs.map(({ id, name, sagaId, chapters, premise, locationIds, characterIds, status }) => ({ id, name, sagaId, chapters, premise, locationIds, characterIds, ...(status ? { status } : {}) }));
const locationSummaries = locations.map(({ id, name, kind, region, chapters, landmarks, arcIds }) => ({ id, name, kind, region, chapters, landmarks, arcIds }));
const out = `/* GENERATED by scripts/build-index.ts — do not edit. Source: src/data/arcs*.ts and locations*.ts. */\nimport type { ArcSummary, LocationSummary } from './arc-index';\nexport const arcSummaries: ArcSummary[] = ${JSON.stringify(arcSummaries)};\nexport const locationSummaries: LocationSummary[] = ${JSON.stringify(locationSummaries)};\n`;
const target = new URL('../src/data/index.generated.ts', import.meta.url);
if (!existsSync(target) || readFileSync(target, 'utf8') !== out) { writeFileSync(target, out); console.log(`index.generated.ts: ${arcSummaries.length} arcs, ${locationSummaries.length} locations`); }
