import type { Arc, Location, Saga } from '../types';
import { sagas } from './sagas';
import { arcSummaries, locationSummaries } from './index.generated';

/** Light arc records for the journey page: everything except the long-form story text (generated by scripts/build-index.ts). */
export type ArcSummary = Pick<Arc, 'id' | 'name' | 'sagaId' | 'chapters' | 'premise' | 'locationIds' | 'characterIds' | 'status'>;
export type LocationSummary = Pick<Location, 'id' | 'name' | 'kind' | 'region' | 'chapters' | 'landmarks' | 'arcIds'>;

export { arcSummaries, locationSummaries, sagas };
export type { Saga };
export const sagaFor = (arc: ArcSummary): Saga | undefined => sagas.find((s) => s.id === arc.sagaId);
export const chapterLabel = (arc: Pick<Arc, 'chapters' | 'status'>): string => arc.status === 'ongoing' ? `Ch. ${arc.chapters[0]} →` : `Ch. ${arc.chapters[0]}–${arc.chapters[1]}`;
